[package]
name = "vesu-liquidator"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
starknet = "0.11.0"
tokio = { version = "1.39.2", features = ["full"] }
url = "2.5.2"
serde = "1.0.207"
serde_yaml = "0.9"
serde_json = "1.0.125"
strum = { version = "0.26", features = ["derive"] }
reqwest = { version = "0.12.5", features = ["json"] }
json = "0.12.4"
bigdecimal = "0.4.5"
lazy_static = "1.5.0"
anyhow = "1.0.86"
futures-util = "0.3.30"

apibara-sdk = { git = "https://github.com/apibara/dna", branch = "main" }
apibara-core = { git = "https://github.com/apibara/dna", branch = "main" }
