[package]
name = "vesu-liquidator"
version = "0.1.0"
edition = "2021"

[dependencies]
starknet = "0.11.0"
tokio = { version = "1.39.2", features = ["full"] }
url = "2.5.2"
serde = "1.0.207"
reqwest = {version = "0.12.5", features = ["json"] }
json = "0.12.4"
bigdecimal = "0.4.5"
lazy_static = "1.5.0"
anyhow = "1.0.86"
