[package]
name = "vesu-liquidator"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://www.vesu.xyz/"
repository = "https://github.com/astraly-labs/Vesu-liquidator"
description = "Liquidator bot for the Vesu Protocol"
readme = "README.md"
keywords = ["vesu", "liquidator", "bot", "starknet"]

[dependencies]
anyhow = "1.0.86"
bigdecimal = "0.4.5"
clap = { version = "4.5.16", features = ["derive"] }
colored = "2.1.0"
dotenvy = "0.15.7"
futures-util = "0.3.30"
lazy_static = "1.5.0"
reqwest = { version = "0.12.5", features = ["json"] }
serde = "1.0.207"
serde_json = "1.0.125"
serde_yaml = "0.9"
starknet = "0.11.0"
strum = { version = "0.26", features = ["derive"] }
tokio = { version = "1.39.3", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.2"

apibara-core = { git = "https://github.com/apibara/dna", branch = "main" }
apibara-sdk = { git = "https://github.com/apibara/dna", branch = "main" }
