---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml

  rust:
    name: Build, Format, Clippy, Machete, LLVM-Cov, Nextest
    uses: ./.github/workflows/rust.yml
